"""Country card colour schemes."""

from dataclasses import dataclass


@dataclass
class CS:
    name: str
    bg: str
    fg1: str
    fg2: str
    text: str

schemes = {
    "AF": CS(name="Afghanistan", bg="black", fg1="red", fg2="green", text="white"),
    "AL": CS(name="Albania", bg="red", fg1="black", fg2="black", text="black"),
    "DZ": CS(name="Algeria", bg="green", fg1="red", fg2="white", text="white"),
    "AD": CS(name="Andorra", bg="yellow", fg1="blue", fg2="red", text="red"),
    "AO": CS(name="Angola", bg="black", fg1="red", fg2="red", text="yellow"),
    "AG": CS(name="Antigua and Barbuda", bg="black", fg1="red", fg2="blue", text="yellow"),
    "AR": CS(name="Argentina", bg="cyan", fg1="white", fg2="white", text="white"),
    "AM": CS(name="Armenia", bg="red", fg1="white", fg2="yellow", text="yellow"),
    "AU": CS(name="Australia", bg="blue", fg1="red", fg2="white", text="white"),
    "AT": CS(name="Austria", bg="white", fg1="red", fg2="red", text="red"),
    "AZ": CS(name="Azerbaijan", bg="cyan", fg1="green", fg2="red", text="red"),
    "BY": CS(name="Belarus", bg="white", fg1="red", fg2="red", text="red"),
    "BE": CS(name="Belgium", bg="red", fg1="yellow", fg2="black", text="black"),
    "BJ": CS(name="Benin", bg="green", fg1="yellow", fg2="red", text="yellow"),
    "BT": CS(name="Bhutan", bg="orange", fg1="yellow", fg2="white", text="white"),
    "BA": CS(name="Bosnia and Herzegovina", bg="blue", fg1="yellow", fg2="yellow", text="yellow"),
    "BI": CS(name="Burundi", bg="green", fg1="red", fg2="white", text="white"),
    "BO": CS(name="Bolivia", bg="yellow", fg1="green", fg2="red", text="red"),
    "BR": CS(name="Brazil", bg="green", fg1="yellow", fg2="blue", text="yellow"),
    "BN": CS(name="Brunei", bg="yellow", fg1="white", fg2="red", text="black"),
    "BD": CS(name="Bangladesh", bg="green", fg1="red", fg2="red", text="red"),
    "BG": CS(name="Bulgaria", bg="green", fg1="red", fg2="white", text="white"),
    "CV": CS(name="Cabo Verde", bg="blue", fg1="white", fg2="red", text="white"),
    "KH": CS(name="Cambodia", bg="blue", fg1="red", fg2="red", text="red"),
    "CM": CS(name="Cameroon", bg="green", fg1="red", fg2="yellow", text="yellow"),
    "CA": CS(name="Canada", bg="red", fg1="white", fg2="white", text="white"),
    "TD": CS(name="Chad", bg="yellow", fg1="navy", fg2="navy", text="navy"),
    "CL": CS(name="Chile", bg="blue", fg1="red", fg2="white", text="white"),
    "CN": CS(name="China", bg="red", fg1="yellow", fg2="yellow", text="yellow"),
    "CO": CS(name="Colombia", bg="red", fg1="yellow", fg2="yellow", text="yellow"),
    "CR": CS(name="Costa Rica", bg="red", fg1="blue", fg2="white", text="white"),
    "HR": CS(name="Croatia", bg="blue", fg1="red", fg2="white", text="white"),
    "CU": CS(name="Cuba", bg="blue", fg1="red", fg2="white", text="white"),
    "CY": CS(name="Cyprus", bg="white", fg1="orange", fg2="orange", text="orange"),
    "CZ": CS(name="Czechia", bg="blue", fg1="red", fg2="white", text="white"),
    "CS": CS(name="Czechoslovakia", bg="blue", fg1="red", fg2="white", text="white"),
    "DK": CS(name="Denmark", bg="red", fg1="white", fg2="white", text="white"),
    "DO": CS(name="Dominican Republic", bg="blue", fg1="red", fg2="white", text="white"),
    "CD": CS(name="Zaire", bg="blue", fg1="red", fg2="yellow", text="yellow"),
    "DD": CS(name="East Germany", bg="black", fg1="red", fg2="yellow", text="grey"),
    "EC": CS(name="Ecuador", bg="blue", fg1="red", fg2="yellow", text="black"),
    "EG": CS(name="Egypt", bg="red", fg1="white", fg2="black", text="black"),
    "EN": CS(name="England", bg="red", fg1="white", fg2="white", text="white"),
    "EE": CS(name="Estonia", bg="cyan", fg1="black", fg2="white", text="black"),
    "ET": CS(name="Ethiopia", bg="blue", fg1="green", fg2="red", text="yellow"),
    "FO": CS(name="Faroe Islands", bg="white", fg1="blue", fg2="blue", text="red"),
    "FJ": CS(name="Fiji", bg="cyan", fg1="blue", fg2="white", text="white"),
    "FI": CS(name="Finland", bg="white", fg1="blue", fg2="blue", text="blue"),
    "FR": CS(name="France", bg="blue", fg1="red", fg2="white", text="white"),
    "GE": CS(name="Georgia", bg="white", fg1="red", fg2="red", text="red"),
    "DE": CS(name="Germany", bg="black", fg1="red", fg2="yellow", text="yellow"),
    "GM": CS(name="Gambia", bg="blue", fg1="red", fg2="green", text="white"),
    "GT": CS(name="Guatemala", bg="cyan", fg1="white", fg2="white", text="white"),
    "GY": CS(name="Guyana", bg="green", fg1="yellow", fg2="red", text="white"),
    "GH": CS(name="Ghana", bg="yellow", fg1="green", fg2="red", text="red"),
    "GR": CS(name="Greece", bg="blue", fg1="white", fg2="white", text="white"),
    "GL": CS(name="Greenland", bg="white", fg1="red", fg2="white", text="red"),
    "GN": CS(name="Guinea", bg="yellow", fg1="red", fg2="green", text="green"),
    "HT": CS(name="Haiti", bg="red", fg1="blue", fg2="blue", text="white"),
    "HK": CS(name="Hong Kong", bg="red", fg1="white", fg2="white", text="white"),
    "HU": CS(name="Hungary", bg="red", fg1="green", fg2="green", text="white"),
    "IS": CS(name="Iceland", bg="blue", fg1="red", fg2="white", text="white"),
    "IN": CS(name="India", bg="orange", fg1="green", fg2="blue", text="white"),
    "ID": CS(name="Indonesia", bg="white", fg1="red", fg2="red", text="red"),
    "IR": CS(name="Iran", bg="green", fg1="red", fg2="white", text="white"),
    "IE": CS(name="Ireland", bg="green", fg1="orange", fg2="white", text="white"),
    "IQ": CS(name="Iraq", bg="black", fg1="red", fg2="white", text="white"),
    "IL": CS(name="Israel", bg="white", fg1="blue", fg2="blue", text="blue"),
    "CI": CS(name="Ivory Coast", bg="orange", fg1="green", fg2="white", text="white"),
    "IT": CS(name="Italy", bg="green", fg1="red", fg2="white", text="white"),
    "JM": CS(name="Jamaica", bg="green", fg1="yellow", fg2="yellow", text="black"),
    "JP": CS(name="Japan", bg="white", fg1="red", fg2="red", text="red"),
    "KZ": CS(name="Kazakhstan", bg="turquoise", fg1="yellow", fg2="yellow", text="yellow"),
    "KE": CS(name="Kenya", bg="red", fg1="black", fg2="darkgreen", text="white"),
    "XK": CS(name="Kosovo", bg="blue", fg1="yellow", fg2="white", text="white"),
    "KG": CS(name="Kyrgyzstan", bg="red", fg1="yellow", fg2="yellow", text="yellow"),
    "LA": CS(name="Laos", bg="red", fg1="navy", fg2="navy", text="white"),
    "LV": CS(name="Latvia", bg="maroon", fg1="white", fg2="white", text="white"),
    "LB": CS(name="Lebanon", bg="white", fg1="green", fg2="red", text="red"),
    "LI": CS(name="Liechtenstein", bg="red", fg1="blue", fg2="blue", text="blue"),
    "LK": CS(name="Sri Lanka", bg="brown", fg1="yellow", fg2="green", text="yellow"),
    "LT": CS(name="Lithuania", bg="green", fg1="red", fg2="yellow", text="yellow"),
    "LU": CS(name="Luxembourg", bg="cyan", fg1="red", fg2="white", text="white"),
    "LY": CS(name="Libya", bg="black", fg1="red", fg2="green", text="white"),
    "MO": CS(name="Macao", bg="green", fg1="white", fg2="white", text="white"),
    "MG": CS(name="Madagascar", bg="green", fg1="red", fg2="white", text="white"),
    "MY": CS(name="Malaysia", bg="blue", fg1="red", fg2="yellow", text="white"),
    "MV": CS(name="Maldives", bg="red", fg1="green", fg2="white", text="white"),
    "MT": CS(name="Malta", bg="red", fg1="white", fg2="white", text="white"),
    "MU": CS(name="Mauritius", bg="blue", fg1="red", fg2="green", text="yellow"),
    "MX": CS(name="Mexico", bg="green", fg1="white", fg2="red", text="brown"),
    "MD": CS(name="Moldova", bg="blue", fg1="red", fg2="yellow", text="yellow"),
    "MC": CS(name="Monaco", bg="red", fg1="white", fg2="white", text="white"),
    "MM": CS(name="Burma", bg="green", fg1="yellow", fg2="red", text="white"),
    "MN": CS(name="Mongolia", bg="blue", fg1="red", fg2="red", text="yellow"),
    "ME": CS(name="Montenegro", bg="red", fg1="yellow", fg2="yellow", text="purple"),
    "MA": CS(name="Morocco", bg="red", fg1="green", fg2="green", text="green"),
    "MZ": CS(name="Mozambique", bg="green", fg1="red", fg2="yellow", text="yellow"),
    "NA": CS(name="Namibia", bg="blue", fg1="red", fg2="green", text="white"),
    "NP": CS(name="Nepal", bg="red", fg1="blue", fg2="white", text="white"),
    "NI": CS(name="Nicaragua", bg="cyan", fg1="white", fg2="white", text="white"),
    "NL": CS(name="Netherlands", bg="blue", fg1="red", fg2="white", text="white"),
    "NZ": CS(name="New Zealand", bg="blue", fg1="red", fg2="white", text="white"),
    "NG": CS(name="Nigeria", bg="green", fg1="white", fg2="white", text="white"),
    "NE": CS(name="Niger", bg="orange", fg1="green", fg2="white", text="white"),
    "MK": CS(name="North Macedonia", bg="red", fg1="yellow", fg2="yellow", text="yellow"),
    "NO": CS(name="Norway", bg="red", fg1="blue", fg2="white", text="white"),
    "XF": CS(name="Overseas France", bg="blue", fg1="red", fg2="white", text="white"),
    "PS": CS(name="Palestine", bg="black", fg1="green", fg2="red", text="white"),
    "PK": CS(name="Pakistan", bg="green", fg1="white", fg2="white", text="white"),
    "PA": CS(name="Panama", bg="white", fg1="red", fg2="red", text="navy"),
    "PH": CS(name="Philippines", bg="blue", fg1="yellow", fg2="red", text="white"),
    "PE": CS(name="Peru", bg="red", fg1="white", fg2="white", text="white"),
    "PL": CS(name="Poland", bg="red", fg1="white", fg2="white", text="white"),
    "PT": CS(name="Portugal", bg="green", fg1="red", fg2="yellow", text="white"),
    "PR": CS(name="Puerto Rico", bg="blue", fg1="red", fg2="white", text="white"),
    "QA": CS(name="Qatar", bg="maroon", fg1="white", fg2="white", text="white"),
    "PY": CS(name="Paraguay", bg="white", fg1="blue", fg2="blue", text="red"),
    "RO": CS(name="Romania", bg="blue", fg1="red", fg2="yellow", text="yellow"),
    "RU": CS(name="Russia", bg="blue", fg1="red", fg2="white", text="white"),
    "WS": CS(name="Samoa", bg="blue", fg1="red", fg2="white", text="white"),
    "SM": CS(name="San Marino", bg="cyan", fg1="white", fg2="white", text="white"),
    "ST": CS(name="São Tomé and Príncipe", bg="green", fg1="red", fg2="yellow", text="black"),
    "AB": CS(name="Scotland", bg="blue", fg1="white", fg2="white", text="white"),
    "SV": CS(name="El Salvador", bg="blue", fg1="white", fg2="white", text="yellow"),
    "RS": CS(name="Serbia", bg="blue", fg1="red", fg2="white", text="white"),
    "SL": CS(name="Sierra Leone", bg="green", fg1="blue", fg2="white", text="white"),
    "SG": CS(name="Singapore", bg="red", fg1="white", fg2="white", text="white"),
    "SK": CS(name="Slovakia", bg="blue", fg1="red", fg2="white", text="white"),
    "SI": CS(name="Slovenia", bg="blue", fg1="red", fg2="white", text="white"),
    "ZA": CS(name="South Africa", bg="green", fg1="red", fg2="blue", text="yellow"),
    "KR": CS(name="South Korea", bg="white", fg1="blue", fg2="red", text="black"),
    "SU": CS(name="Soviet Union", bg="red", fg1="yellow", fg2="yellow", text="yellow"),
    "ES": CS(name="Spain", bg="red", fg1="gold", fg2="gold", text="gold"),
    "SR": CS(name="Suriname", bg="green", fg1="yellow", fg2="red", text="white"),
    "SE": CS(name="Sweden", bg="blue", fg1="yellow", fg2="yellow", text="yellow"),
    "CH": CS(name="Switzerland", bg="red", fg1="white", fg2="white", text="white"),
    "SY": CS(name="Syria", bg="red", fg1="green", fg2="white", text="white"),
    "TW": CS(name="Taiwan", bg="blue", fg1="red", fg2="white", text="white"),
    "TJ": CS(name="Tajikistan", bg="green", fg1="red", fg2="yellow", text="white"),
    "TH": CS(name="Thailand", bg="blue", fg1="red", fg2="white", text="white"),
    "TL": CS(name="Timor-Leste", bg="red", fg1="yellow", fg2="black", text="white"),
    "TN": CS(name="Tunisia", bg="red", fg1="white", fg2="white", text="white"),
    "TR": CS(name="Turkey", bg="red", fg1="white", fg2="white", text="white"),
    "TG": CS(name="Togo", bg="green", fg1="yellow", fg2="red", text="white"),
    "TM": CS(name="Turkmenistan", bg="green", fg1="red", fg2="white", text="white"),
    "UA": CS(name="Ukraine", bg="blue", fg1="yellow", fg2="yellow", text="yellow"),
    "AE": CS(name="United Arab Emirates", bg="black", fg1="green", fg2="red", text="white"),
    "GB": CS(name="United Kingdom", bg="navy", fg1="red", fg2="white", text="white"),
    "US": CS(name="United States", bg="navy", fg1="red", fg2="white", text="white"),
    "UY": CS(name="Uruguay", bg="white", fg1="blue", fg2="blue", text="blue"),
    "UZ": CS(name="Uzbekistan", bg="cyan", fg1="white", fg2="green", text="red"),
    "VE": CS(name="Venezuela", bg="blue", fg1="red", fg2="yellow", text="white"),
    "VN": CS(name="Vietnam", bg="red", fg1="yellow", fg2="yellow", text="yellow"),
    "XX": CS(name="Winner", bg="blue", fg1="green", fg2="white", text="white"),
    "XI": CS(name="Northern Ireland", bg="white", fg1="red", fg2="red", text="red"),
    "WA": CS(name="Wales", bg="white", fg1="green", fg2="green", text="red"),
    "EH": CS(name="Western Sahara", bg="black", fg1="green", fg2="red", text="white"),
    "YU": CS(name="Yugoslavia", bg="blue", fg1="yellow", fg2="red", text="white"),
    "ZW": CS(name="Zimbabwe", bg="yellow", fg1="green", fg2="red", text="black"),
}
